.catalog:
  name: "QoQa Odoo"
  version: "v9.0.0.1"
  description: "Odoo"
  uuid: qoqa-odoo-9001
  minimum_rancher_version: v0.44.0
  question:
    - variable: "DB_USER"
      label: "Login of database"
      description: "Username to use when connecting to DB"
      type: "string"
      required: true
      default: "odoo"
    - variable: "DB_PASSWORD"
      label: "Password of database"
      description: "Password for odoo dedicated database (default: odoo)"
      type: "password"
      required: true
      default: "odoo"
    - variable: "DB_NAME"
      label: "Database name"
      description: "name of database to create for odoo"
      type: "string"
      required: true
      default: "odoo"
    - variable: "SCENARIO_MAIN_TAG"
      label: "Scenario tag"
      description: "Tag used in scenarii for this project e.g. c2c"
      required: true
    - variable: "ADMIN_PASSWD"
      label: "admin_passwd"
      description: "Master password for database management"
      type: "password"
      required: false
