# -*- coding: utf-8 -*-
from . import account_bank_statement
from . import account_invoice
from . import account_move
from . import account_move_line
from . import account_journal_dashboard
from . import crm_claim
from . import ir_attachment
from . import purchase_order
from . import procurement
from . import procurement
from . import product
from . import res_partner
from . import sale_order
from . import stock_move
from . import stock_move_operation_link
from . import stock_picking
from . import stock_quant_package
from . import stock_pack_operation
