odoo:
  tty: true
  stdin_open: true
  build: ./odoo/
  command: "odoo.py --load=web,connector"
  ports:
    - 8069
    - 8072
  links:
    - db:db
  volumes:
    # for dev only (todo: add configuration files per env)
    - "./odoo/src:/opt/odoo/src"
    - "./odoo/local-src:/opt/odoo/local-src"
    - "./odoo/external-src:/opt/odoo/external-src"
    - "./odoo/features:/opt/odoo/features"
    - "./odoo/data:/opt/odoo/data"
  volumes_from:
    - dataodoo
  environment:
    - SCENARIO_MAIN_TAG=qoqa
    - DB_USER=odoo
    - DB_PASSWORD=odoo
    - DB_NAME=odoodb
    - ADMIN_PASSWD=mijaebohb8Thae1g
    - RUNNING_ENV=dev
    - DEMO=odoo
    - ODOO_CONNECTOR_CHANNELS=root:4

db:
  image: camptocamp/postgresql:pg9.5-latest
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
    - PG_SYSTEM_SHARED_BUFFERS=256MB
    - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
    - PG_SYSTEM_WAL_BUFFERS=8MB
    - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
  volumes_from:
    - datadb
  ports:
    - 5432

# can be useful for dev when longpolling is required
nginx:
  image: camptocamp/odoo-nginx:9.0
  ports:
    - 80:80
  links:
    - odoo:odoo

dataodoo:
  image: debian:jessie
  volumes:
    - /data/odoo
  command: "true"

datadb:
  image: debian:jessie
  volumes:
    - /var/lib/postgresql/data
  command: "true"
