external-db:
  image: rancher/external-service

odoo:
  image: camptocamp/qoqa_openerp:latest
  links:
  - external-db:db
  volumes:
    - dataodoo:/data/odoo
  environment:
    - SCENARIO_MAIN_TAG=${SCENARIO_MAIN_TAG}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    - ADMIN_PASSWD=${ADMIN_PASSWD}
    - RUNNING_ENV=${RUNNING_ENV}
    - DEMO=${DEMO}
    - WORKERS=${WORKERS}
    - MAX_CRON_THREADS=${MAX_CRON_THREADS}
    - LOG_LEVEL=${LOG_LEVEL}
    - LOG_HANDLER=${LOG_HANDLER}
    - DB_MAXCONN=${DB_MAXCONN}
    - LIMIT_MEMORY_SOFT=${LIMIT_MEMORY_SOFT}
    - LIMIT_MEMORY_HARD=${LIMIT_MEMORY_HARD}
    - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
    - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}

nginx:
  image: camptocamp/odoo-nginx:9.0
  ports:
    - 80:80
  links:
    - odoo:odoo

# Load balanced used only to setup SSL easily
lb:
  ports:
  - 443:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
  tty: true
  image: rancher/load-balancer-service
  links:
  - nginx:nginx
  stdin_open: true
