external-db:
  image: rancher/external-service

odoo:
  image: camptocamp/qoqa_openerp:latest
  links:
  - external-db:db
  volumes:
    - dataodoo:/data/odoo
  environment:
    - SCENARIO_MAIN_TAG=${SCENARIO_MAIN_TAG}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    - ADMIN_PASSWD=${ADMIN_PASSWD}
    - RUNNING_ENV=${RUNNING_ENV}

nginx:
  image: camptocamp/odoo-nginx:9.0
  ports:
    - 80:80
  links:
    - odoo:odoo
