{'name': '[DEPRECATED]',
 'summary': "stock_orderpoint_creator renamed stock_orderpoint_generator",
 'version': '100',
 'author': 'Camptocamp',
 'maintainer': 'Camptocamp',
 'license': 'AGPL-3',
 'category': 'category',
 'complexity': "easy",  # easy, normal, expert
 'depends': ['stock_orderpoint_generator'],
 'website': 'www.camptocamp.com',
 'data': [],
 'test': [],
 'installable': True,
 'auto_install': False,
 }
